stages:
  - build
  - test
  - deploy
build-job:
  stage: build
  script:
    - echo "Build stage Running"
test-job:
  stage: test
  script:
    - echo "Test Stage Running"
deploy-job:
  stage: deploy
  script:
    - echo "Deploy Stage Running"


