name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build stage
        run: echo "Build stage Running"

      - name: Test stage
        run: echo "Test stage Running"

      - name: Deploy stage
        run: echo "Deploy stage Running"